apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: openfiles-http-list-files
spec:
  components:
    - name: http-list-files
      type: component
      properties:
        image: file://./target/wasm32-wasip2/release/http_list_files.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            labels:
              openfiles: "true"
        - type: link
          properties:
            target: wasi-http
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
        - type: link
          properties:
            target: wasi-filesystem
            namespace: wasi
            package: filesystem
            interfaces: [types, preopens]
